version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: terraform-opensearch
    environment:
      - cluster.name=terraform-cluster
      - node.name=terraform-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - terraform-net

  search-ui:
    build: ./ui
    container_name: terraform-search-ui
    ports:
      - "3000:3000"
    environment:
      - ELASTICSEARCH_URL=http://opensearch:9200
      - ES_INDEX=terraform-resources
      - PORT=3000
    depends_on:
      - opensearch
    networks:
      - terraform-net

  localstack:
    image: localstack/localstack:3.0
    container_name: terraform-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack-data:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - terraform-net

  terraform-indexer:
    build: ./backend
    container_name: terraform-indexer
    ports:
      - "8000:8000"
    environment:
      - MODE=local
      - S3_BUCKET=terraform-states
      - S3_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - ES_HOSTS=http://opensearch:9200
      - ES_INDEX=terraform-resources
      - FILESYSTEM_WATCH_DIRECTORY=/app/tfstates
      - FILESYSTEM_ENABLED=true
    volumes:
      - ./tfstates:/app/tfstates
      - ./examples:/app/examples
      - ./.env:/app/.env
    depends_on:
      - opensearch
      - localstack
    networks:
      - terraform-net

volumes:
  opensearch-data:
  localstack-data:

networks:
  terraform-net:
    driver: bridge